In [1]:
import pandas as pd
vaccine = pd.read_csv("training_set_features.csv")
labels = pd.read_csv("training_set_labels.csv")
test = pd.read_csv("test_set_features.csv")
vaccine.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [2]:
vaccine.set_index('respondent_id',inplace = True)
labels.set_index('respondent_id',inplace = True)
test.set_index('respondent_id',inplace = True)
dataset= pd.concat([vaccine,labels],axis=1)
dataset.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,xyz_vaccine,seasonal_vaccine
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

In [3]:
X = dataset.drop(['xyz_vaccine','seasonal_vaccine'],axis=1)
X.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [4]:
y1 = dataset['xyz_vaccine']
y1.head()

respondent_id
0    0
1    0
2    0
3    0
4    0
Name: xyz_vaccine, dtype: int64

In [5]:
y2 = dataset['seasonal_vaccine']
y2.head()

respondent_id
0    0
1    1
2    0
3    1
4    0
Name: seasonal_vaccine, dtype: int64

In [6]:
num_col = X.select_dtypes(include=['int64','float64']).columns
num_test = test.select_dtypes(include=['int64','float64']).columns
num_test

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
       'household_children'],
      dtype='object')

In [7]:
cols_to_fill = [ 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
       'household_children']
test_cols_to_fill = [ 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
       'household_children']

In [8]:
X[cols_to_fill]=X[cols_to_fill].fillna(X[cols_to_fill].median())
test[test_cols_to_fill]=test[test_cols_to_fill].fillna(test[test_cols_to_fill].median())

In [9]:
X.isnull().sum()

xyz_concern                        0
xyz_knowledge                      0
behavioral_antiviral_meds          0
behavioral_avoidance               0
behavioral_face_mask               0
behavioral_wash_hands              0
behavioral_large_gatherings        0
behavioral_outside_home            0
behavioral_touch_face              0
doctor_recc_xyz                    0
doctor_recc_seasonal               0
chronic_med_condition              0
child_under_6_months               0
health_worker                      0
health_insurance                   0
opinion_xyz_vacc_effective         0
opinion_xyz_risk                   0
opinion_xyz_sick_from_vacc         0
opinion_seas_vacc_effective        0
opinion_seas_risk                  0
opinion_seas_sick_from_vacc        0
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
rent_or_own                     2042
employment_status               1463
hhs_geo_region                     0
census_msa                         0
household_adults                   0
household_children                 0
employment_industry            13330
employment_occupation          13470
dtype: int64

In [10]:
X.shape

(26707, 35)

In [11]:
X.dropna(inplace=False).shape

(11942, 35)

In [12]:
cat_col = X.select_dtypes(include=['object']).columns
test_cat_col = test.select_dtypes(include=['object']).columns

In [13]:
for col in cat_col:
    mode_value=X[col].mode()[0]
    X[col]=X[col].fillna(mode_value)
for col in test_cat_col:
    mode_value=test[col].mode()[0]
    test[col]=test[col].fillna(mode_value)

In [14]:
X = pd.get_dummies(X, columns=cat_col)
test = pd.get_dummies(test, columns=test_cat_col)

In [15]:
X.isnull().sum()

xyz_concern                       0
xyz_knowledge                     0
behavioral_antiviral_meds         0
behavioral_avoidance              0
behavioral_face_mask              0
                                 ..
employment_occupation_vlluhbov    0
employment_occupation_xgwztkwe    0
employment_occupation_xqwwgdyp    0
employment_occupation_xtkaffoo    0
employment_occupation_xzmlyyjv    0
Length: 105, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[num_col]=scaler.fit_transform(X[num_col])
test[num_test]=scaler.fit_transform(test[num_test])
X.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,employment_occupation_qxajmpny,employment_occupation_rcertsgn,employment_occupation_tfqavkke,employment_occupation_ukymxvdu,employment_occupation_uqqtjvyb,employment_occupation_vlluhbov,employment_occupation_xgwztkwe,employment_occupation_xqwwgdyp,employment_occupation_xtkaffoo,employment_occupation_xzmlyyjv
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,-0.681849,-2.044279,-0.226293,-1.634957,-0.272097,-2.177944,-0.74589,1.404892,0.687870,-0.503893,...,False,False,False,False,False,False,False,False,True,False
1,1.518373,1.197027,-0.226293,0.611637,-0.272097,0.459149,-0.74589,1.404892,0.687870,-0.503893,...,False,False,False,False,False,False,True,False,False,False
2,-0.681849,-0.423626,-0.226293,0.611637,-0.272097,-2.177944,-0.74589,-0.711798,-1.453764,-0.503893,...,False,False,False,False,False,False,False,False,True,False
3,-0.681849,-0.423626,-0.226293,0.611637,-0.272097,0.459149,1.34068,-0.711798,-1.453764,-0.503893,...,False,False,False,False,False,False,False,False,True,False
4,0.418262,-0.423626,-0.226293,0.611637,-0.272097,0.459149,1.34068,-0.711798,0.687870,-0.503893,...,False,False,False,False,False,False,False,False,False,False

In [17]:
from sklearn.linear_model import LogisticRegression
model1= LogisticRegression(max_iter=1000)
model2 = LogisticRegression(max_iter=1000)
model1.fit(X,y1)
model2.fit(X,y2)
pred_probab1 = model1.predict_proba(test)
pred_probab2 = model2.predict_proba(test)

In [18]:
pred_probab1

array([[0.94434479, 0.05565521],
       [0.95299088, 0.04700912],
       [0.5852396 , 0.4147604 ],
       ...,
       [0.86422502, 0.13577498],
       [0.93773016, 0.06226984],
       [0.41270761, 0.58729239]])

In [19]:
pred_probab2

array([[0.70702198, 0.29297802],
       [0.95531664, 0.04468336],
       [0.40640885, 0.59359115],
       ...,
       [0.80046906, 0.19953094],
       [0.63068219, 0.36931781],
       [0.45754262, 0.54245738]])

In [20]:

test.head()

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,employment_occupation_qxajmpny,employment_occupation_rcertsgn,employment_occupation_tfqavkke,employment_occupation_ukymxvdu,employment_occupation_uqqtjvyb,employment_occupation_vlluhbov,employment_occupation_xgwztkwe,employment_occupation_xqwwgdyp,employment_occupation_xtkaffoo,employment_occupation_xzmlyyjv
respondent_id,,,,,,,,,,,,,,,,,,,,,
26707,0.416677,1.196455,-0.228202,0.605151,-0.272726,0.458421,1.361067,-0.711659,0.677712,-0.507268,...,False,False,False,False,False,False,False,False,False,False
26708,-0.692524,-0.430992,-0.228202,-1.652480,-0.272726,-2.181402,-0.734717,-0.711659,-1.475552,-0.507268,...,False,False,False,False,False,False,False,True,False,False
26709,0.416677,1.196455,-0.228202,-1.652480,3.666683,0.458421,1.361067,1.405168,0.677712,-0.507268,...,False,False,False,False,False,False,False,False,False,False
26710,-0.692524,-0.430992,-0.228202,-1.652480,-0.272726,-2.181402,-0.734717,-0.711659,-1.475552,1.971346,...,False,False,False,False,False,False,False,False,True,False
26711,1.525878,-0.430992,4.382091,0.605151,-0.272726,0.458421,1.361067,1.405168,0.677712,-0.507268,...,False,False,False,False,False,False,False,False,False,False

In [21]:
part1 = pd.DataFrame(pred_probab1[:,1])
part2 = pd.DataFrame(pred_probab2[:,1])
part3 = pd.DataFrame(test.index)
result = pd.concat([part3,part1,part2],axis=1)
result.head()

   respondent_id         0         0
0          26707  0.055655  0.292978
1          26708  0.047009  0.044683
2          26709  0.414760  0.593591
3          26710  0.499530  0.881396
4          26711  0.163621  0.471616

In [22]:
result = result.set_index('respondent_id')

In [23]:
result=result.rename(columns={0:'h1n1_vaccine',1:'seasonal_vaccine'})

In [24]:
result

               h1n1_vaccine  h1n1_vaccine
respondent_id
26707              0.055655      0.292978
26708              0.047009      0.044683
26709              0.414760      0.593591
26710              0.499530      0.881396
26711              0.163621      0.471616
...                     ...           ...
53410              0.345285      0.535089
53411              0.102981      0.283994
53412              0.135775      0.199531
53413              0.062270      0.369318
53414              0.587292      0.542457

[26708 rows x 2 columns]

In [25]:
result.to_csv('result.csv')